
platform :ios, '11.0'

target 'CCTIOS' do
  
  pod 'LookinServer', :configurations => ['Debug']
  pod "MJRefresh"
  pod 'YYWebImage'
  pod "TTGTagCollectionView"
  pod 'R.swift'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'SkeletonView'
  pod "PromiseKit/CorePromise", "~> 6.8"
  pod 'DDGScreenShot', '~> 1.1.6'
  pod 'DKLogger'
  pod 'CHIPageControl', '~> 0.1.3'
  pod 'CRBoxInputView'
  pod 'KMPlaceholderTextView'
  pod 'mob_pushsdk'
  pod 'JXSegmentedView'
  pod 'JXPagingView/Paging'
  pod 'HandyJSON', '~> 5.0.2'
  pod "Haptica"
  pod 'SideMenuSwift'
  pod 'SwipeCellKit'
  pod 'FSCalendar'
  pod 'TextFieldEffects'
  pod 'EachNavigationBar'
  pod 'NTMonthYearPicker'
  pod 'RxSwift','5.1.2'
  pod 'RxGesture'
  pod 'RxSwiftExt'
  pod 'RxCocoa'
  
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
