
platform :ios, '11.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'CCTIOS' do
  
  pod 'LookinServer', :configurations => ['Debug']
  pod "MJRefresh"
  pod 'YYWebImage'
  pod "TTGTagCollectionView"
  pod 'R.swift'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'SkeletonView'
  pod "PromiseKit/CorePromise", "~> 6.8"
  pod 'DDGScreenShot', '~> 1.1.6'
  pod 'DKLogger'
  pod 'CHIPageControl', '~> 0.1.3'
  pod 'CRBoxInputView'
  pod 'KMPlaceholderTextView'
  pod 'mob_pushsdk'
  pod 'JXSegmentedView'
  pod 'JXPagingView/Paging'
  pod 'HandyJSON', '~> 5.0.2'
  pod "Haptica"
  pod 'SideMenuSwift'
  pod 'SwipeCellKit'
  
#  pod 'SwifterSwift'
  
  config = use_native_modules!
  use_react_native!(path: config['reactNativePath'])

  
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
